export const routes = {
  login: "/login",
  workspaceRoot: (wid: string) => `/w/${wid}`,
  workspaceOverview: (wid: string) => `/w/${wid}`,
  workspaceSettings: (wid: string) => `/w/${wid}/settings`,
  admin: (wid: string) => `/w/${wid}/admin`,
  adminMembers: (wid: string) => `/w/${wid}/admin/members`,
  adminProjects: (wid: string) => `/w/${wid}/admin/projects`,
  adminAudit: (wid: string) => `/w/${wid}/admin/audit`,
  projectRoot: (wid: string, pid: string) => `/w/${wid}/p/${pid}`,
  projectOverview: (wid: string, pid: string) => `/w/${wid}/p/${pid}/overview`,
  projectTeam: (wid: string, pid: string) => `/w/${wid}/p/${pid}/team`,
  projectModules: (wid: string, pid: string) => `/w/${wid}/p/${pid}/modules`,
  projectRepo: (wid: string, pid: string) => `/w/${wid}/p/${pid}/repo`,
  projectLibrary: (wid: string, pid: string) => `/w/${wid}/p/${pid}/library`,
  projectLibraryNew: (wid: string, pid: string) => `/w/${wid}/p/${pid}/library/new`,
  projectImports: (wid: string, pid: string) => `/w/${wid}/p/${pid}/imports`,
  projectReviews: (wid: string, pid: string) => `/w/${wid}/p/${pid}/reviews`,
  projectDiffs: (wid: string, pid: string) => `/w/${wid}/p/${pid}/diffs`,
  projectAI: (wid: string, pid: string) => `/w/${wid}/p/${pid}/ai`,
  projectAgent: (wid: string, pid: string) => `/w/${wid}/p/${pid}/agent`,
  projectAgentMemory: (wid: string, pid: string) => `/w/${wid}/p/${pid}/agent/memory`,
  projectPlans: (wid: string, pid: string) => `/w/${wid}/p/${pid}/plans`,
  projectReports: (wid: string, pid: string) => `/w/${wid}/p/${pid}/reports`
} as const;
